Task1 with tests
aq-simei/11th_card_trick pull request #1
Opened 2022-03-08 16:08 UTC by aq-simei

2022-03-08 20:01 UTC, iagodahlem requested changes

2022-03-08 20:01 UTC, iagodahlem commented on src/tests/create_deck.test.js
> +    expect(deck).toMatchSnapshot();
Não é muito recomendável fazer snapshots pra funções que não sejam componentes. Pra casos assim que são funções, o ideal é fazer testes unitários mesmo com os retornos da função.

2022-03-09 17:51 UTC, nolleto commented on src/tests/create_deck.test.js
> +    expect(DECK.length).toBe(52);
Dica: você pode usar [. toHaveLength(number)](https://jestjs.io/pt-BR/docs/expect#tohavelengthnumber) aqui

```suggestion
    expect(DECK).toHaveLength(52);
```

2022-03-09 17:51 UTC, nolleto commented on src/tests/create_deck.test.js
> +  it("Checks if created a full deck", () => {
Algumas dicas com as mensagens....

Geralmente não é comum usar `if` porque você pode usar um `describe` para criar um cenário.
Na hora de escrever algo dentro do `it` pense que isso faz parte da frase tipo:
> it is a beautiful day 🎶
Nesse caso seu `it` ficaria:
```js
it('is a beautiful day 🎶', () => { ... })
```

Como isso é um `it` você tem que conjugar o verbo no Simple Preset.

Para completar, lembre-se q isso irá gerar uma frase que iremos ler no terminal.

Um exemplo _best_: 
```js
const fullName = (user) => `${user.firstName} ${user.lastName}`

describe('fullName', () => {
  it('returns the full name', () => {})

  describe('when lastName is empty', () => { // um cenario de uso
    it('returns the first name', () => {})
  })

  describe('when firstName is empty', () => { // outro cenario de uso
    it('returns the last name', () => {})
  })
})
```

Terminal:
```cmd
fullName
  returns the full name
  when lastName is empty
    returns the first name
  when firstName is empty
    returns the last name
```

Aonde você vai ler
> fullName returns the full name
> fullName when lastName is empty returns the first name
> fullName when firstName is empty returns the last name

2022-03-10 11:35 UTC, iagodahlem requested changes

2022-03-10 11:35 UTC, iagodahlem commented on src/App.js
> +import { TrickDeck } from "./Components/TrickComponents/TrickDeck/index";
Faltou arrumar aqui.

2022-03-10 11:35 UTC, iagodahlem commented on src/Components/TrickComponents/TrickDeck/index.jsx
> +import { DECK } from "../../../utils/create_deck";
É uma boa renomear os arquivos tambem pra seguir o padrão.

2022-03-10 11:35 UTC, iagodahlem commented on src/tests/__snapshots__/create_deck.test.js.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
Vamos remover esse teste de snapshot. Snapshots devem ser feitas apenas para componentes.

2022-03-10 12:16 UTC, aq-simei commented on src/Components/TrickComponents/TrickDeck/index.jsx
> +import { DECK } from "../../../utils/create_deck";
algum padrão sugerido? 
Ou fica a meu critério?

2022-03-10 12:16 UTC, aq-simei commented on src/tests/__snapshots__/create_deck.test.js.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
Ok, farei a deleção

2022-03-11 12:12 UTC, iagodahlem commented on src/Components/TrickComponents/TrickDeck/index.jsx
> +import { DECK } from "../../../utils/create_deck";
O mais comum em JS é usar uma combinação de PascalCase pra arquivos que são classes ou componentes e camelCase pro resto, como arquivos de CSS e utils assim.

2022-03-11 12:15 UTC, iagodahlem approved these changes
Tirando a nomenclatura dos arquivos, me parece tudo certo. Arrumando isso já pode dar merge. 👍

2022-03-11 12:15 UTC, iagodahlem commented on src/tests/create_deck.test.js
> +    expect(DECK).toContainEqual(
Acho que aqui poderia ser um .toEqual mesmo, já que tu tá testando o baralho todo, teve algum problema usando ele? 🤔

2022-03-11 12:31 UTC, merged